[package]
name = "polkadot-overseer-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Generate an overseer including builder pattern and message wrapper from a single struct."

[dependencies]
polkadot-overseer-gen-proc-macro = { path = "./proc-macro" }
tracing = "0.1"
